[project]
name = "pygame-templates"
version = "0.1.1"
description = "Examples of game blanks using the pygame, for beginners"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame-ce>=2.5.3",
]
